name: FastAPI Nano

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Test
        run: |
          pip install docker-compose
          chmod +x ./scripts/docker_ci.sh
          ./scripts/docker_ci.sh
